### ISSUE TITLE
مشکل ست کردن شکن در اوبونتو

### ISSUE THREAD

**Issue by anvaari** [GreatBahram/shecan-cli#2]
سلام. 
من وقتی توی اوبونتو 20.04 
`shecan set --temporary` 
رو ران میکنم. 
ارور زیر رو میگیرم. 

> ERROR: Could not move resolv file (/etc/resolv.conf) to  /tmp/resolv.conf: [Errno 17] File exists: '../run/resolvconf/resolv.conf' -> '/tmp/resolv.conf'

**Comment by GreatBahram** [comment]
سلام
نسخه جدید رو نصب کنید و یکبار دیگه تست بگیرید

مرسی

**Comment by anvaari** [comment]
ممنونم ازتون
ولی  با اجرای 
`shecan set --temporary` 
این ارور رو گرفتم :

> 2021-01-20 23:15:19,367 ERROR: Could not update resolv file: [Errno 13] Permission denied: '/etc/resolv.conf'

با اجرا 
`sudo -E $(which shecan) set --temporary`
هم این ارور

> 2021-01-20 23:16:31,143 ERROR: Could not move resolv file (/etc/resolv.conf) to  /tmp/resolv.conf: [Errno 13] Permission denied: '/tmp/resolv.conf'

**Comment by masoud-msk** [comment]
Maybe the `/tmp/resolv.conf` file exists already. Delete it and try again.
```bash
sudo rm -f /tmp/resolv.conf
```

**Comment by anvaari** [comment]
ممنون. ولی مشکل جای دیگه بود که کلا دو تا سرویس بودن که خودشون 
resolve.conf 
رو بازنویسی میکردن اتوماتیک. با این اموزش تونستم حل کنم مشکل رو و کلا دستی ست کردم.
[How to take back control of /etc/resolv.conf on Linux](https://www.ctrl.blog/entry/resolvconf-tutorial.html)

**Comment by edrisranjbar** [comment]
I think @GreatBahram might need to close this issue bcz it is unnecessary and resolved.
